### ISSUE TITLE
Implement setup - development environment - Dockerfiles, etc - figure out how to mount dag directory into aws-mwaa-local-runner Docker container. Avoid using our own fork.

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#469]

**Comment by christinklez** [comment]
Barbara posted a question on the AWS MWAA slack; the response provided a very complex approach.

Propose exploring rebase automation options. Also will see if official AWS provides any recommendations.

**Comment by barbarahui** [comment]
AWS says they will consider our request to modify their code for ease of use with dags stored in an external repo: https://apache-airflow.slack.com/archives/CCRR5EBA7/p1690405849653759

In the meantime, I've made quick and dirty use of a github action from marketplace: https://github.com/ucldc/aws-mwaa-local-runner/blob/v2.5.1/.github/workflows/pull_upstream.yml

This will pull and merge in any upstream changes from the aws repo to our fork. Rebasing would be nicer, but since we'll very rarely be making any changes to our fork, I don't think it's worth taking the time to figure it out.

I've also updated the README on how to do local-runner development for rikolti here: https://github.com/ucldc/rikolti/tree/mwaa-airflow-dev/airflow

**Comment by barbarahui** [comment]
This PR is related to this issue but I can't figure out how to link it: https://github.com/ucldc/aws-mwaa-local-runner/pull/1
