### ISSUE TITLE
Amy and Barbara to set Barbara and Chad up to generate validation reports

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#491]

**Comment by amywieliczka** [comment]
Done! https://github.com/ucldc/rikolti/tree/rikolti_bucket_template contains the shell scripts used to do this. 

Some handy links to have available when doing the work: 
- [Registry API URL Template](https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&mapper_type=chapman_oai_dc&ready_for_publication=true) - can update mapper_type to the mapper type in question
- [Registry UI](https://registry.cdlib.org) - use the right hand side column to see mapper types, find collections by mapper or fetcher type
- [Mapper Types Google Drive Document](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640) 
- [CouchDB Stage](https://harvest-stg.cdlib.org/couchdb/_utils/database.html?ucldc/_all_docs)
- [CouchDB Prod](https://harvest-prd.cdlib.org/couchdb/_utils/database.html?ucldc/_all_docs)
- [Rikolti Data Validation Google Drive Folder](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) - where you'll upload validation runs split by mapper type and date run. 
- [CouchDB Prod isShownAt report URL Template](https://harvest-prd.cdlib.org/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2227305%22&field=isShownAt) - can update field to isShownBy, and key to the collection ID in question

**Comment by amywieliczka** [comment]
Here's a proposed workflow: 

1. Check out the `rikolti_bucket_template` branch 
2. `cp -r rikolti_bucket_template rikolti_bucket`, since `rikolti_bucket` is in .gitignore, you can then 
3. Check out the feature branch that you would like to test (or create a temporary merge branch of the feature branch merged into main, if relevant)
4. Run `./rikolti_bucket/jobs/harvest.sh <legacy_mapper_name>` or `./rikolti_bucket/jobs/harvest_collection.sh <collection_id>`, as the case may be. 
5. Resolve any issues (sometimes the `harvest.sh` job gets hung up on something or other)
6. Once `rikolti_bucket` has all the collections in question in it, `mv rikolti_bucket <job argument: legacy_mapper_name or collection_id>-<today's date>`
7. Upload to google drive for evaluation
8. (optional) It is pretty easy to write custom validators, so if there are lots of validation errors that are obviously excusable (http vs. https in urls, for example), write some custom validators and re-run the process.

**Comment by amywieliczka** [comment]
Notes on Custom Validators:

Most frequently, I will create a custom validator class within the mapper module for which it is coupled (ex: `FlickrValidator` lives in `flickr_mapper.py`). The custom validator typically implements exactly 1 function (`__init__`) and typically defines one or a few custom validation functions which are added to the Validator by calling Validator.add_validatable_field() in the subclassed initialization function. 

`Validator.add_validatable_field()` takes the five properties of a /validation definition/: `field`, `type`, `validations`, `level` (optional) and `mode` (optional). `add_validatable_field()` also takes a `replace` parameter, which has a default value of True. `add_validatable_field()` by default overwrites any existing validation definitions for the same field name. If `replace` is False and an existing validation definition for that field name already exists, then the specified validation definition does not replace the original. The default set of validation definitions is defined here: https://github.com/ucldc/rikolti/blob/main/metadata_mapper/validator/validator.py#L448. 

Validation Definitions are comprised of 5 properties: 
`field` - the name of the field to validate. 
`type` - the expected type of the field in the Rikolti data
`validations` - a list of /validation functions/ to run. Though this is a list, order does not matter - these validations aren't chained in some way such that if an earlier one produces an error, it short circuits. 
`level` (optional) - ValidationLogLevel
`mode` (optional) - ValidationMode

Note: Mode is a bit tricky and plays a significant role in the default `content_match` validation - check the validation_mode.py module. 

Due to the fact that `add_validatable_field` does a wholesale replacing of all validation functions associated with a given field, I typically copy the existing validation definition for the field in question, and then update the `validations` list to include the custom validation functions my custom validator class defines. 

Validation functions are static methods of the Validator. Their function signature is of the format: `def validation_function_name (validation_definition, rikolti_value, comparison_value)`. If the validation fails, the validation function returns a string to be printed in the validation report. 

Finally, don't forget to register your custom validator with your mapper by setting `validator=CustomValidatorClassName` as a class variable on the relevant Vernacular class (right underneath `RecordClass=CustomRecordClassName`)

Sample Custom Validators

1. Flickr Validator: https://github.com/ucldc/rikolti/blob/a211578fb728809d0be7cf060b3f9c10ada19b45/metadata_mapper/mappers/flickr/flickr_mapper.py#L132
2. SPPL Validator: https://github.com/ucldc/rikolti/blob/a211578fb728809d0be7cf060b3f9c10ada19b45/metadata_mapper/mappers/flickr/sppl_mapper.py#L78
3. Chapman Validator: https://github.com/ucldc/rikolti/blob/1e06e8816d3a7f29a5e5cbe79e9ce57c03e1f441/metadata_mapper/mappers/oai/chapman_mapper.py#L60
4. CCA Vault Validator: https://github.com/ucldc/rikolti/blob/542e8841e962b0f2248f24590806183380bee186/metadata_mapper/mappers/oai/cca_vault_mapper.py - this one is quite a bit different, as described in CCA Vault ID Workaround PR request: https://github.com/ucldc/rikolti/pull/484
