### ISSUE TITLE
oai.yosemite validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#606]
### oai.yosemite issues
- [ ] coverage & spatial: currently mapping `<dcterms:spatial>` to both coverage and spatial. Please map to only spatial. (Note however that we have some messy spatial and coverage mapping logic in solr_updater.py : https://cdlib.slack.com/archives/CQ534NT47/p1699395989918789?thread_ts=1699393088.260719&cid=CQ534NT47)
- [ ] spatial: should be in an array (currently a string).

See examples: #26989 ([2023-10-25](https://docs.google.com/spreadsheets/d/1l4TtiML3aU-lT9IpfnH0vkYZAD5JRP1J-ccLWf5v5V8/edit#gid=1076201431)); #27631 ([2023-10-25](https://docs.google.com/spreadsheets/d/1r0nH-ZdafkvesKBiwWYvFSsY-lhxt0ic4YwIAiNFBnc/edit#gid=1029340956))

***
#### Verify whether these are addressed by the base oai mapper updates
- [ ] source: map source -- [note: this may get addressed in the base oai mapper]

**Comment by amywieliczka** [comment]
Made the following updates - not yet pushed up, but making a note here regarding some of the details and will push up momentarily. 

- mapping: `is_shown_by` and `is_shown_at` both filtered identifiers for identifiers with "npsgallery.nps.gov" in the string (along with other unique filters for each), but this subdomain has changed to "nps.gov/npgallery", updated filter accordingly
- validating: updated `is_shown_at`, `is_shown_by`, and `identifier` validation logic to ignore this specific subdomain discrepancy
- validating: updated `coverage` and `spatial` validation logic to report out exclusively lossy discrepancies, instances where not all solr values exist in rikolti, but not additive discrepancies, instances where all solr values exist in rikolti as well as new values
- validating: records from collection `26989` all had the same value for `is_shown_at`: "https://npgallery.nps.gov/AssetDetail/3331008b-6cb0-4583-85f7-b3a93f7e074d", but in Rikolti, their `is_shown_at` value is unique to the record. the `is_shown_at_improvements` validator and the `after_validation` function check to make sure this new `is_shown_at` url is at the proper URL location and contains the proper object ID

Spatial is now a list, and source seems to be mapped - I didn't see any validation report errors for either of those. I did not remove the mapping to coverage due to the complexities of the `solr_updater`. Every collection has spatial and coverage values that are identical. We can revisit removing one or the other post MVP.

**Comment by amywieliczka** [comment]
Is closed by #696
