### ISSUE TITLE
Image server strategy to dos (tbd)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#615]
Notes from a previous discussion: https://docs.google.com/document/d/1g1L5I_6sNwjLP5fjYigeyqrSXDvf4AW4w-VCE64XKIo/edit#bookmark=id.exlcrobm2rj1

**Comment by amywieliczka** [comment]
### Thumbnailer

The thumbnailer is a tiny (43 line) subclass of pilbox which adds a configurable `S3_ENDPOINT` and a URL handler to parse out an md5 from the request url in order to compose an s3 source for generating thumbnail images. Pilbox is a python thumbnail server built on Pillow (for image processing) and tornado (for serving http requests). Pilbox is currently deprecated, but does seem to be able to run on Pillow 9.5 and python 3.8 somehow. I haven't been able to get this stack running on my local machine, but building the Dockerfile does produce a functional image that I was able to run locally. I was also able to deploy this image to Fargate containers with an `S3_ENDPOINT` pointing at the Rikolti content. An image built from the same Dockerfile is already deployed to an elasticbeanstalk instance with an `S3_ENDPOINT` pointing at the legacy image content. 

The thumbnailer requires that all images are available via an http request, so I had to configure the s3 bucket where we store Rikolti thumbnails to a public location. 

The thumbnailer currently sits as an origin to Calisphere's cloudfront distribution. There might be some cacheing layer provided by `pilbox`, but as far as I can tell, we aren't using it. We're just relying on Cloudfront to provide us with cacheing. 

IAS does want Cloudfront to connect to origins over https. Currently, Cloudfront connects to the thumbnailer over http only. I did do some work to try to get the existing elasticbeanstalk's application load balancer to listen on 443, but was never able to successfully set up Cloudfront to connect to the thumbnailer over https. 

- pilbox 1.3.4 - released on August 11, 2018, deprecated on December 1, 2019
- Pillow 9.5 - released on April 1, 2023, Pillow 10.1 is latest
- python 3.8 - reasonably modern, at time of writing, python 3.12 is latest

Unless we can use IIIF server to serve our thumbnails, I think we should keep using the existing thumbnailer but deploy it on ECS. I think we should ask for IAS' help in turning my click-ops deployment of the container into a production-ready and cloudformation described deployment of the thumbnailer - this would involve correctly configuring load balancing, an ECS namespace for a persistent service URL (is that how you do it?), listening on 443 (application currently listens on 8888) and getting https set up, and setting up this ECS service as a cloudfront origin, potentially across AWS accounts?

I'm investigating the IIIF server next.

**Comment by christinklez** [comment]
The Rikolti team discussed a short-term (MVP) and long-term (post-MVP) strategy. See [notes here](https://docs.google.com/document/d/1g1L5I_6sNwjLP5fjYigeyqrSXDvf4AW4w-VCE64XKIo/edit#bookmark=id.7okd9ic87ulk)

**Immediate next steps (for MVP) include:**

- Move the thumbnailer to Fargate (would be good to get help from IAS and provisioned for production) (#651)
- Deploy potto loris for Rikolti content and moved into PAD (#652)
- Begin to look at the Nuxeo fetcher/mapper, since that is the source for Potto Loris (#619)
