### ISSUE TITLE
ucsd_blacklight.ucsd_blacklight mapper validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#620]
**spatial / coverage / subject:** map `geographic_tesim` to `spatial` only (this is currently getting mapped 3 times, to coverage/subject/spatial. Please do not map `geographic_tesim` to `coverage`. The current mapping to `subject` is okay.)

![Image](https://github.com/ucldc/rikolti/assets/32110172/b1e7a361-081a-4b53-9892-f721e5709b0a)

**Comment by lthurston** [comment]
This isn't happening in the mapper as it turns out. There was mapping configuration for `coverage`, but removing it didn't resolve this because `map_couch_to_solr_doc()` method in mapper is copying the spatial field to coverage:

`                'coverage': filter_blank_values(record.get('spatial')),`

Should I remove that line?

**Comment by aturner** [comment]
@lthurston Lucas, following on our brief discussion of the UCSD mapper yesterday -- we'd like to accept the new Rikolti mapper as-is, where it's taking data from `geographic_tesim` and mapping it to `spatial` (which is also then subsequently getting copied to `coverage` from a subsequent `map_couch_to_solr_doc()` function). We did some further digging into the legacy code, and it turns out that the Calisphere front-end only displays one of those data values (not both) in the front end -- and it's going to be messy to try to refactor the `map_couch_to_solr_doc()` function and/or front-end at this time. It's something we can come back to once we cut over to Rikolti / after this year.

Going that route, we can close out this PR: [`Remove coverage field mapping in blacklight #622`](https://github.com/ucldc/rikolti/pull/622)

**Comment by christinklez** [comment]
See: https://github.com/ucldc/rikolti/issues/620#issuecomment-1802659599

This mapper is accepted! @amywieliczka @barbarahui
