### ISSUE TITLE
Refactor Rikolti to accommodate Nuxeo complex objects (& revisit Nuxeo fetcher/mapper)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#667]

**Comment by amywieliczka** [comment]
This is awaiting @bibliotechy's review of #675 - we stepped through it in a call and he mentioned he'd be taking a look at it, but I haven't heard back. I've generally been continuing to develop on top of this work under the presumption that if changes are requested, they'll be minor rather than a shift in overall approach. Once this lands, we can start running validations on nuxeo collections, and it should also reduce the number of halting errors in the validation pipeline by continuing other collections even if one collection fails.
