### ISSUE TITLE
Trigger jobs by the Airflow API from the Registry (to handle bulk jobs)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#744]

**Comment by amywieliczka** [comment]
### Access

I can't seem to access the Airflow API programmatically. 

I can connect to the [Airflow API](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/api/v1/dags/validate_by_mapper_type) via a web browser with an active Cognito-MWAA session, but can't seem to access it programmatically. There's no mention of the Airflow API in the MWAA user guide, either, and [many](https://www.reddit.com/r/aws/comments/17jlilm/mwaa_access_to_airflows_rest_api/) [reports](https://stackoverflow.com/questions/67884770/is-it-possible-to-access-the-airflow-api-in-aws-mwaa?noredirect=1#comment119989884_67884770) of [issues](https://stackoverflow.com/questions/66344988/how-can-i-enable-the-api-in-aws-managed-workflows-for-apache-airflow) accessing the Airflow API, all of which point toward using the Airflow CLI. 

There seems to be two ways to get access to Airflow: 
1. `create-web-login-token` [The documentation](https://docs.aws.amazon.com/mwaa/latest/userguide/call-mwaa-apis-web.html) for `create-web-login-token` only shows examples of using the web token to access `https://<airflow>/aws_mwaa/aws-console-sso?login=true#<web token>`, but never `https://<airflow>/api/v1/<api endpoint>`. This is what our cognito lambda function uses once a user has logged in via cognito. It seems that after this point, the token isn't used any longer, and a browser session is established for access. 
2. `create-cli-token` [The documentation](https://docs.aws.amazon.com/mwaa/latest/userguide/call-mwaa-apis-cli.html) for `create-cli-token`, on the other hand, provides many examples of hitting Airflow programmatically, but not via the API at `https://<airflow>/aws_mwaa/cli`, and I was also able to find this sample of [invoking dags from a lambda function](https://docs.aws.amazon.com/mwaa/latest/userguide/samples-lambda.html)

Once I had set up a local bash shell with my an AWS Access Key Id, Secret Access Key, and Session Token, I was able to run the following commands locally to get a CLI Token. This token is good for 60 seconds. 

```sh
CLI_JSON=$(aws mwaa create-cli-token --name pad-airflow-mwaa --region us-west-2) && \
CLI_TOKEN=$(echo $CLI_JSON | jq -r '.CliToken') && \
WEB_SERVER_HOSTNAME=$(echo $CLI_JSON | jq -r '.WebServerHostname')
```

### CLI Commands

I was then able to issue the following Airflow CLI commands:

#### [List dags](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#list_repeat2)

```sh
# list all DAGS in the airflow instance
CLI_RESULTS=$(
    curl --request POST https://$WEB_SERVER_HOSTNAME/aws_mwaa/cli \
         --header "Authorization: Bearer $CLI_TOKEN" \
         --header "Content-Type: text/plain" \
         --data-raw "dags list") && \
CLI_OUT=$(echo $CLI_RESULTS | jq -r '.stdout' | base64 --decode) && \
CLI_ERROR=$(echo $CLI_RESULTS | jq -r '.stderr' | base64 --decode)
```

Response from the Airflow CLI Endpoint are json objects with `stdout` and `stderr` keys. The values for `stdout` and `stderr` are both base64 encoded. 

#### [Trigger a Dag](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#trigger)

```sh
CLI_RESULTS=$(
    curl --request POST https://$WEB_SERVER_HOSTNAME/aws_mwaa/cli \
         --header "Authorization: Bearer $CLI_TOKEN" \
         --header "Content-Type: text/plain" \
         --data-raw "dags trigger -o json validate_by_mapper_type"
    ) && \
CLI_OUT=$(echo $CLI_RESULTS | jq -r '.stdout' | base64 --decode) && \
CLI_ERROR=$(echo $CLI_RESULTS | jq -r '.stderr' | base64 --decode)
```

In this case, CLI_OUT looks something like:

```sh
[2024-02-02T02:34:21.768+0000] {{__init__.py:42}} INFO - Loaded API auth backend: airflow.api.auth.backend.session
[{"conf": {}, "dag_id": "validate_by_mapper_type", "dag_run_id": "manual__2024-02-02T02:34:22+00:00", "data_interval_end": "2024-02-02T02:34:22+00:00", "data_interval_start": "2024-02-02T02:34:22+00:00", "end_date": null, "external_trigger": "True", "last_scheduling_decision": null, "logical_date": "2024-02-02T02:34:22+00:00", "run_type": "manual", "start_date": null, "state": "queued"}]
```

Of course, since we get a log statement from Airflow, we can't directly pipe this to jq, but we are able to get structured data with a dag_run_id. 

#### [List Runs](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#list-runs)

There doesn't seem to be an Airflow CLI command for getting information about a DAG run, comparable to the [GET DagRun API endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_run). But we can list out *all* runs of a given dag:

```sh
CLI_RESULTS=$(
    curl --request POST https://$WEB_SERVER_HOSTNAME/aws_mwaa/cli \
         --header "Authorization: Bearer $CLI_TOKEN" \
         --header "Content-Type: text/plain" \
         --data-raw "dags list-runs -d validate_by_mapper_type -o json"
    ) && \
CLI_OUT=$(echo $CLI_RESULTS | jq -r '.stdout' | base64 --decode) && \
CLI_ERROR=$(echo $CLI_RESULTS | jq -r '.stderr' | base64 --decode)
```

This is capable of getting piped directly into jq: `echo $CLI_OUT | jq '.[] | select(.run_id == "manual__2024-02-02T01:55:18+00:00")'`, for example. We'll have thousands, and likely tens of thousands, of runs of this one dag, though. There's no documentation regarding when Airflow starts truncating this list, or how AWS manages sending very long lists of DAG runs via AWS' cli api. 

#### [Query State](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#state)

By specifying a Dag Run's `execution_date`:

```sh
CLI_RESULTS=$(
    curl --request POST https://$WEB_SERVER_HOSTNAME/aws_mwaa/cli \
         --header "Authorization: Bearer $CLI_TOKEN" \
         --header "Content-Type: text/plain" \
         --data-raw "dags state validate_by_mapper_type 2024-02-02T01:55:18+00:00"
    ) && \
CLI_OUT=$(echo $CLI_RESULTS | jq -r '.stdout' | base64 --decode) && \
CLI_ERROR=$(echo $CLI_RESULTS | jq -r '.stderr' | base64 --decode)
```

But it's unclear what execution_date actually is - in these examples, it corresponds to the second half of Dag Run ID split on `__`, and also to `logical_date` and also to `data_interval_start`. 

This returns a simple string "failed", for example, with no other information about the Dag Run.

**Comment by amywieliczka** [comment]
Given that MWAA doesn't seem to want to play nice, I think it might make the most sense to embed into our Airflow DAG some tasks that write data about the Dag Run to a known s3 location. That way, the Registry can use the dag trigger CLI command, but otherwise not interact directly with Airflow, and instead read from a known s3 location. At some point later, we can substitute out the s3 location for event bridge or some other messaging system, but Rikolti is already really good at writing to s3, so this seems simplest at the moment. 

@bibliotechy any other ideas given these constraints?

**Comment by amywieliczka** [comment]
This was a helpful reminder on how the login flow works: https://drive.google.com/file/d/16JZAWJv27PpXsf60imyAE5as8_TkYMXw/view?usp=drive_link
