### ISSUE TITLE
Nuxeo collection harvesting fails at "content harvesting" stage (UC Merced/Cooperative Extension complex image objects)

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#856]
Running full harvests of 2 Nuxeo collections (UC Merced/Cooperative Extension) -- both are collections of complex image objects (scanned images of documents), getting the same error for both failing at content harvesting stage. There are no specific logs to point to from Airflow (also not sure how to link to the specific DAG runs):

1] Error: fails at "map page" stage
Registry #23389
Rikolti mapper: nuxeo.nuxeo
Airflow Run ID: manual__2024-04-10T18:08:52+00:00
https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/graph?execution_date=2024-04-10+18%3A08%3A52%2B00%3A00

2] Error: fails at "content harvesting" stage
Registry #27851
Rikolti mapper: nuxeo.nuxeo
Airflow Run ID: manual__2024-04-10T18:09:15+00:00
https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/graph?execution_date=2024-04-10+18%3A09%3A15%2B00%3A00

**Comment by barbarahui** [comment]
@aturner @christinklez I'd like to try running one of these large collections from scratch (and not try rerunning any failed mapped tasks) so that I can examine the logs and hone in on what exactly is causing the workers to be killed. OK if I kick off `23389` via the Airflow UI?

**Comment by barbarahui** [comment]
@aturner @christinklez I'm figured it's OK for me to go ahead and kick this off. Leaving this note here just FYI :)

**Comment by christinklez** [comment]
Thank you, @barbarahui! That sounds like a great plan!

**Comment by barbarahui** [comment]
OK, I think my updates have fixed things. I ran `27143` as a test and it's successfully on stage (although the `validate_collection` task failed -- but I think I remember that's a known issue?)

Unfortunately you will need rerun any large collections that previously failed **from scratch**, i.e. fetch the metadata again. This is because the changes I made batch up the data differently starting with the fetching.

You should now see a max of 50 `[]mapped_tasks` for the `map_page[]` and `content_harvest[]` steps. For very large collections, it can take a long time to run things, particularly the content harvest task. Airflow will try polling ECS for up to 4 hours before giving up and saying that the task has failed. So hopefully that's enough time for even very large collections to run. If not, let me know.

**Comment by barbarahui** [comment]
Related PRs:
https://github.com/ucldc/rikolti/pull/875
https://github.com/ucldc/rikolti/pull/877

**Comment by barbarahui** [comment]
I increased the time that Airflow will wait for content harvester tasks finish to 24 hours. I reran monster collection 23389 and it took 10 hours for a couple of the tasks to run (way longer than I expected; I guess they must have a lot of huge media files). I'm not sure how big our biggest collection is, but hopefully 24 hours is enough time.

PR: https://github.com/ucldc/rikolti/pull/878
