### ISSUE TITLE
[bug] Alameda Free Library's institution landing page does not load and results in an error

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#861]
Alameda Free Library has 3 collections that were ETL'd:
- https://calisphere-stage.cdlib.org/collections/27162/
- https://calisphere-stage.cdlib.org/collections/27163/
- https://calisphere-stage.cdlib.org/collections/27545/

The collections look great! The institution name is also listed on the Sitewide Institutions listing. However, when clicking on the "institution" link, the page results in an error.

**Comment by amywieliczka** [comment]
This is related to #862:

Here's the `sort_collection_data` value from Solr:

`california of the past alameda:California of the Past: Alameda:https://registry.cdlib.org/api/v1/collection/27162/`

We want that to have `::` delimiters, so we convert `:` to `::` which results in this value in our OpenSearch index: 

`california of the past alameda::California of the Past:: Alameda::https:://registry.cdlib.org/api/v1/collection/27162/`

Calisphere seems to think the collection ID for this sort_collection_data value is ` Alameda::https:://registry.cdlib.org/api/v1/collection/27162/` and is rather understandably croaking at trying to access [https://registry.cdlib.org/api/v1/ Alameda::https:://registry.cdlib.org/api/v1/collection/27162/](https://registry.cdlib.org/api/v1/ Alameda::https:://registry.cdlib.org/api/v1/collection/27162//)

--------------

What we actually want is this `sort_collection_data` value:

`california of the past alameda::California of the Past: Alameda::27162`

PR #946 addresses updating `https://registry.cdlib.org/api/v1/collection/27162/` to `27162` for future ETL harvests, but doesn't address the fact that `California of the Past: Alameda` becomes `California of the Past:: Alameda` and I'm not sure there's any great programatic way to catch this case other than hardcoding the name into our ETL mapper. @barbarahui I think you handled `:` in the collection name by getting the `.split(':')[-1]` not too long ago - do you remember what context that was in? 

Since this mapper won't (hopefully) be long-lived anyway, I think I'll go ahead and hard code it, and then we should either reharvest everything from this institution, or write an open search updater to run against everything from this institution.

**Comment by amywieliczka** [comment]
With Calisphere's debug flag turned on, we are getting some better error messages about why it's failing to load: https://calisphere-stage.cdlib.org/institution/252/collections/

**Comment by amywieliczka** [comment]
PR #946 now handles `:` in the collection name in a generic way - solved by assuming:

```python
sortable_name = sort_collection_data.split(':')[0]
display_name = ':'.join(sort_collection_data.split(':')[1:-2])
registry_url = ':'.join(sort_collection_data.split(':')[-2:])
```

**Comment by amywieliczka** [comment]
I re-mapped these collections and this is now fixed!
